import type {
  EnvelopeId,
  Prediction,
} from "@finality/shared";

/* ============================================================================
 * Submit Prediction Response
 * ============================================================================
 *
 * Returned by the protocol adapter after a prediction has been
 * successfully created and submitted to the Finality network.
 *
 * The response contains the prediction along with the generated
 * envelope identifier and digest, which can later be used to
 * verify or track the prediction.
 * ============================================================================
 */

export interface SubmitPredictionResponse {
  /**
   * Unique envelope identifier generated by the protocol.
   */
  readonly envelopeId: EnvelopeId;

  /**
   * The created prediction.
   */
  readonly prediction: Prediction;

  /**
   * Canonical digest submitted to Finality.
   */
  readonly digest: string;

  /**
   * Whether the submission was accepted.
   */
  readonly accepted: boolean;

  /**
   * Human-readable status message.
   */
  readonly message?: string;
}