/* ============================================================================
 * Finality Status
 * ============================================================================
 */

export enum FinalityStatus {
  PENDING = "pending",

  VERIFIED = "verified",

  FAILED = "failed",
}

/* ============================================================================
 * Verification Proof
 * ============================================================================
 */

export interface FinalityProof {
  /**
   * Proof returned by the Finality network.
   */
  readonly value: string;

  /**
   * Proof algorithm.
   */
  readonly algorithm: string;
}

/* ============================================================================
 * Finality Receipt
 * ============================================================================
 */

export interface FinalityReceipt {
  /**
   * Envelope identifier.
   */
  readonly envelopeId: string;

  /**
   * Canonical digest.
   */
  readonly digest: string;

  /**
   * Verification status.
   */
  readonly status: FinalityStatus;

  /**
   * Optional proof.
   */
  readonly proof?: FinalityProof;

  /**
   * Optional transaction identifier.
   */
  readonly transactionId?: string;

  /**
   * Verification timestamp.
   */
  readonly verifiedAt?: string;
}

/* ============================================================================
 * Submission Result
 * ============================================================================
 */

export interface FinalitySubmissionResult {
  /**
   * Whether submission succeeded.
   */
  readonly accepted: boolean;

  /**
   * Receipt generated by Finality.
   */
  readonly receipt: FinalityReceipt;
}

/* ============================================================================
 * Verification Result
 * ============================================================================
 */

export interface FinalityVerificationResult {
  /**
   * Whether verification succeeded.
   */
  readonly verified: boolean;

  /**
   * Receipt after verification.
   */
  readonly receipt: FinalityReceipt;

  /**
   * Optional failure reason.
   */
  readonly reason?: string;
}